name: sembast_sample
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0


  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sembast: ^3.4.0+6

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

